

CFLAGS = -O0 -g

all:
	gcc ${CFLAGS} char_val.c -o char_val.o 
	gcc ${CFLAGS} char_length.c -o char_length.o 
	gcc ${CFLAGS} 2_dimensional_char_array.c -o 2_dimensional_char_array.o

clean:
	rm  char_val.o char_length.o 2_dimensional_char_array.o 

